# ========== 资料栏 ========== #
# 头像路径
avatar: /avatar/qiu.jpg
# 博主名字，不填写该字段则默认采用Hexo配置文件中的author字段
author: tabris
# 博客签名
signature: Loser
# 社交账号
social:
  email: //604925267@qq.com
  github: //github.com/tabris233
  zhihu: //www.zhihu.com/people/dong-quan-71/activities
  weibo: //weibo.com/u/1810108861
  linkedin: //http://www.linkedin.com/in/%E5%85%A8-%E8%91%A3-b72617144/
  # wechat and qq should be a path of qr-code image
  wechat:  /assets/tabris-weixin.png
  qq: /assets/tabris-qq.png
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  v2ex: 
  others: 
  rss:   

# 友链
friends:
  baidu: //www.baidu.com
  google: //www.google.com
  zhangking: //zhangkingsasa
  tabris's csdn(旧博客): //blog.csdn.net/qq_33184171/
# about页面
about:
  # 是否启用about页
  enable: true
  # about页头图
  image: /intro/dsgl.jpg

# ========== 站点 ========== #
# 网站的title，每篇文章后面也会加上此字段利于SEO
SEO_title: tabris's Blog
# 显示在网站头图上的主标题
main_title: tabris's Blog.
# 显示在网站头图上的副标题
subtitle: With the low level of hard work of most people, there is no chance to fight for talent.
# 主页头图
site_header_image: /intro/zewg-yq.jpg
# 文章页默认头图
post_header_image: /intro/jxjy-2B.jpg
# 404页头图
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== 评论插件 ========== #
# 目前支持直接添加Livere，Disqus，Gitment，畅言及友言，填写插件对应的字段即可启用。
# 如果想添加其他评论插件，在custom.ejs中添加即可。
comment:
  # Livere 官网：https://livere.com/ 'http://oumn0o088.bkt.clouddn.com/404.jpg'
  livere_uid: MTAyMC8zMzU4MS8xMDEzNg
  # Disqus 官网：https://disqus.com/
  disqus_shortname:
  # 畅言 官网：http://changyan.kuaizhan.com/
  changyan_appid:
  changyan_conf:
  # Gitment 官网：https://github.com/imsun/gitment
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:
  # 友言 官网: http://www.uyan.cc/
  youyan_uid:

# ========== 统计 ========== #
# 是否开启不蒜子阅读量统计
busuanzi: true
# 百度统计(填写siteID)
baidu_analytics:
# Google统计(填写siteID)
google_analytics:
# CNZZ统计
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# 首页的文章摘要字数(默认300，填0则不显示摘要)
truncate_length: 200
# enable toc
toc: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
